/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "vmiids_rpc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
enqueuedetectionmodule_1(char *arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, ENQUEUEDETECTIONMODULE,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
dequeuedetectionmodule_1(char *arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, DEQUEUEDETECTIONMODULE,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
enqueuenotificationmodule_1(char *arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, ENQUEUENOTIFICATIONMODULE,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
dequeuenotificationmodule_1(char *arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, DEQUEUENOTIFICATIONMODULE,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
stopids_1(int *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, STOPIDS, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat
loadsharedobject_1(char *arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, LOADSHAREDOBJECT,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
