/*
 * vmistop.cpp
 *
 *  Created on: Jun 28, 2010
 *      Author: kittel
 */

/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "../vmiids/vmiids_rpc.h"


void
simp_prog_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	char *enqueuedetectionmodule_1_arg1;
	enum clnt_stat retval_2;
	int result_2;
	char *dequeuedetectionmodule_1_arg1;
	enum clnt_stat retval_3;
	int result_3;
	char *enqueuenotificationmodule_1_arg1;
	enum clnt_stat retval_4;
	int result_4;
	char *dequeuenotificationmodule_1_arg1;
	enum clnt_stat retval_5;
	int result_5;

#ifndef	DEBUG
	clnt = clnt_create (host, SIMP_PROG, SIMP_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = enqueuedetectionmodule_1(enqueuedetectionmodule_1_arg1, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_2 = dequeuedetectionmodule_1(dequeuedetectionmodule_1_arg1, &result_2, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_3 = enqueuenotificationmodule_1(enqueuenotificationmodule_1_arg1, &result_3, clnt);
	if (retval_3 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_4 = dequeuenotificationmodule_1(dequeuenotificationmodule_1_arg1, &result_4, clnt);
	if (retval_4 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_5 = stopids_1(&result_5, clnt);
	if (retval_5 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	simp_prog_1 (host);
exit (0);
}
