/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VMIIDS_RPC_H_RPCGEN
#define _VMIIDS_RPC_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


#define SIMP_PROG 555555555
#define SIMP_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define ENQUEUEDETECTIONMODULE 1
extern  enum clnt_stat enqueuedetectionmodule_1(char *, int *, CLIENT *);
extern  bool_t enqueuedetectionmodule_1_svc(char *, int *, struct svc_req *);
#define DEQUEUEDETECTIONMODULE 2
extern  enum clnt_stat dequeuedetectionmodule_1(char *, int *, CLIENT *);
extern  bool_t dequeuedetectionmodule_1_svc(char *, int *, struct svc_req *);
#define ENQUEUENOTIFICATIONMODULE 3
extern  enum clnt_stat enqueuenotificationmodule_1(char *, int *, CLIENT *);
extern  bool_t enqueuenotificationmodule_1_svc(char *, int *, struct svc_req *);
#define DEQUEUENOTIFICATIONMODULE 4
extern  enum clnt_stat dequeuenotificationmodule_1(char *, int *, CLIENT *);
extern  bool_t dequeuenotificationmodule_1_svc(char *, int *, struct svc_req *);
#define STOPIDS 5
extern  enum clnt_stat stopids_1(int *, CLIENT *);
extern  bool_t stopids_1_svc(int *, struct svc_req *);
#define LOADSHAREDOBJECT 6
extern  enum clnt_stat loadsharedobject_1(char *, int *, CLIENT *);
extern  bool_t loadsharedobject_1_svc(char *, int *, struct svc_req *);
extern int simp_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ENQUEUEDETECTIONMODULE 1
extern  enum clnt_stat enqueuedetectionmodule_1();
extern  bool_t enqueuedetectionmodule_1_svc();
#define DEQUEUEDETECTIONMODULE 2
extern  enum clnt_stat dequeuedetectionmodule_1();
extern  bool_t dequeuedetectionmodule_1_svc();
#define ENQUEUENOTIFICATIONMODULE 3
extern  enum clnt_stat enqueuenotificationmodule_1();
extern  bool_t enqueuenotificationmodule_1_svc();
#define DEQUEUENOTIFICATIONMODULE 4
extern  enum clnt_stat dequeuenotificationmodule_1();
extern  bool_t dequeuenotificationmodule_1_svc();
#define STOPIDS 5
extern  enum clnt_stat stopids_1();
extern  bool_t stopids_1_svc();
#define LOADSHAREDOBJECT 6
extern  enum clnt_stat loadsharedobject_1();
extern  bool_t loadsharedobject_1_svc();
extern int simp_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_VMIIDS_RPC_H_RPCGEN */
